Traceback (most recent call last):
  File "C:\Users\owner\Downloads\FSND-Virtual-Machine\vagrant\logs_analysis.py", line 40, in <module>
    popular_articles()
  File "C:\Users\owner\Downloads\FSND-Virtual-Machine\vagrant\logs_analysis.py", line 5, in popular_articles
    db = psycopg2.connect(database="news")
  File "C:\Python27\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

[Finished in 2.3s]